### PR TITLE
WIP: Continuation of modularisation

### PR DESCRIPTION
**Pull request by CumpsD**
Follow up PR for https://github.com/KevinDockx/HttpCacheHeaders/pull/57 cleaned up the first go of the WIP :)

I'll commit some more on this PR when I have extracted some other parts

Don't merge it yet please :)

- [x] Support injecting custom store for validation/ETags #11
- [x] Allow custom GenerateKey method #53
- [x] Allow configuring that the eTags generated should be considered weak eTags. #22
- [x] Allow custom ETag functions #6
- [x] Allow multiple datetime formats? #29

### CODE REVIEW

**Comment by CumpsD** [comment]
@KevinDockx, it's ready for review :) I think I'm done with the modular parts for now.

**Comment by CumpsD** [comment]
For fun and giggles, here's how an implementation of a custom `IStoreKeyGenerator` looks:

```csharp
namespace Legacy.Api.Infrastructure
{
    using System.Text.RegularExpressions;
    using System.Threading.Tasks;
    using Common.Infrastructure;
    using Marvin.Cache.Header;
    using Marvin.Cache.Headers;
    using Marvin.Cache.Headers.Interfaces;
    using Microsoft.AspNetCore.Http;

    public class RedisStoreKeyGenerator : IStoreKeyGenerator
    {
        private const string MunicipalityCacheKey = "legacy/municipality:{0}.{1}";
        private static readonly Regex MunicipalityRegex = new Regex(@"/v1/gemeenten/(?<id>\d*)", RegexOptions.Compiled | RegexOptions.ExplicitCapture);

        private const string BuildingCacheKey = "legacy/building:{0}.{1}";
        private static readonly Regex BuildingRegex = new Regex(@"/v1/gebouwen/(?<id>\d*)", RegexOptions.Compiled | RegexOptions.ExplicitCapture);

        private static readonly IStoreKeyGenerator DefaultStoreKeyGenerator = new DefaultStoreKeyGenerator();

        public Task<StoreKey> GenerateStoreKey(
            HttpRequest request,
            ValidationModelOptions validationModelOptions)
        {
            var resourcePath = request.Path.ToString().ToLowerInvariant();

            if (resourcePath.StartsWith("/v1/gemeenten/"))
                return GenerateStoreKey(request, validationModelOptions, resourcePath, MunicipalityRegex, MunicipalityCacheKey);

            if (resourcePath.StartsWith("/v1/gebouwen/"))
                return GenerateStoreKey(request, validationModelOptions, resourcePath, BuildingRegex, BuildingCacheKey);

            return DefaultStoreKeyGenerator.GenerateStoreKey(request, validationModelOptions);
        }

        private static Task<StoreKey> GenerateStoreKey(
            HttpRequest request,
            ValidationModelOptions validationModelOptions,
            string resourcePath,
            Regex regex,
            string cacheKeyFormat)
        {
            var regexResult = regex.Match(resourcePath);

            if (!regexResult.Success)
                return DefaultStoreKeyGenerator.GenerateStoreKey(request, validationModelOptions);

            var requestHeaders = request.GetTypedHeaders();
            var acceptType = requestHeaders.DetermineAcceptType();

            return Task.FromResult(new StoreKey
            {
                { "cacheKey", string.Format(cacheKeyFormat, regexResult.Groups["id"], acceptType.ToString()).ToLowerInvariant() }
            });
        }
    }
}
```

**Comment by CumpsD** [comment]
@KevinDockx I added one more extra, instead of having to create instances on the call to `AddHttpCacheHeaders` it is now also possible to pass in `Func`s to support DI from other services.

**Comment by CumpsD** [comment]
Also for fun, an example of a Redis store:

```csharp
namespace Legacy.Api.Infrastructure
{
    using System;
    using System.Globalization;
    using System.Threading.Tasks;
    using Marvin.Cache.Headers;
    using Marvin.Cache.Headers.Interfaces;
    using StackExchange.Redis;

    public class RedisStore : IValidationValueStore
    {
        private const string ETagKey = "eTag";
        private const string ETagTypeKey = "eTagType";
        private const string LastModifiedKey = "lastModified";

        private readonly ConnectionMultiplexer _redis;

        public RedisStore(ConnectionMultiplexer redis) => _redis = redis;

        public async Task<ValidationValue> GetAsync(StoreKey key)
        {
            var db = _redis.GetDatabase();

            var redisValues =
                await db.HashGetAsync(key.ToString(), new RedisValue[] {ETagKey, ETagTypeKey, LastModifiedKey});

            if (redisValues.Length != 3 ||
                redisValues[0].IsNullOrEmpty ||
                redisValues[1].IsNullOrEmpty ||
                redisValues[2].IsNullOrEmpty)
                return null;

            var eTag = redisValues[0].ToString();
            var eTagType = Enum.Parse<ETagType>(redisValues[1].ToString(), true);

            var lastModified = DateTimeOffset.ParseExact(
                redisValues[2].ToString(),
                "O",
                CultureInfo.InvariantCulture);

            return new ValidationValue(new ETag(eTagType, eTag), lastModified);
        }

        public async Task SetAsync(StoreKey key, ValidationValue eTag)
        {
            var db = _redis.GetDatabase();

            await db.HashSetAsync(key.ToString(), new[]
            {
                new HashEntry(ETagKey, eTag.ETag.Value),
                new HashEntry(ETagTypeKey, eTag.ETag.ETagType.ToString()),
                new HashEntry(LastModifiedKey, eTag.LastModified.ToString("O", CultureInfo.InvariantCulture)),
            }, CommandFlags.FireAndForget);
        }
    }
}
```

**Comment by CumpsD** [comment]
This is how we are using it now:

```csharp
.AddHttpCacheHeaders(
    expirationModelOptions =>
    {
        expirationModelOptions.CacheLocation = CacheLocation.Private;
        expirationModelOptions.NoStore = false;
        expirationModelOptions.NoTransform = true;

        expirationModelOptions.MaxAge = 12 * 60 * 60; // Hours, Minutes, Second
        expirationModelOptions.SharedMaxAge = 12 * 60 * 60; // Hours, Minutes, Second
    },
    validationModelOptions =>
    {
        validationModelOptions.NoCache = false;
        validationModelOptions.MustRevalidate = true;
        validationModelOptions.ProxyRevalidate = true;

        validationModelOptions.VaryByAll = false;
        validationModelOptions.Vary = new List<string> { "Accept", "Accept-Encoding" };
    },
    storeKeyGeneratorFunc: _ => new RedisStoreKeyGenerator(),
    storeFunc: x => new RedisStore(x.GetRequiredService<ConnectionMultiplexer>()))
```

**Comment by CumpsD** [comment]
And it is working nicely :p Planned to be deployed soon ;)

**Comment by KevinDockx** [comment]
Alright!  :)  I'm going to merge this into the modularcomponents branch and have a look.  By the way, those two implementations could make a great start for a Marvin.HttpCache.Headers.Redis repo / nuget package (or any namespace you prefer) ;-)

**Pull request merged**
