### PR TITLE
Add tests for extensions

### PR DESCRIPTION
**Pull request by KenBonny**
Hope this helps, take a look and let me know what you think of it. :)

### CODE REVIEW

**Comment by KevinDockx** [comment]
Thanks for this! :)  I see there's a merge conflict, probably has to do with the merge I did from Maarten's PR.  The references packages should be v1.0.0 packages to stay in line with the most recent LTS (long term support) release of ASP.NET Core.  v1.1.0 packages are currently part of the "Current" release, not LTS.  

Could you quickly check if your code still works on v1.0.0?   All the rest looks good, so if that's the case I'll merge :)

**Comment by KenBonny** [comment]
I'll check tonight.

**Comment by KenBonny** [comment]
Ok, check again, the problems should be gone. :)

**Comment by KevinDockx** [comment]
Thanks! :)

**Pull request merged**
